groups:
- name: destiny
  jobs:
  - test-destiny

resources:
- name: destiny
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf-experimental/destiny.git

jobs:
- name: test-destiny
  public: true
  plan:
  - get: destiny
    trigger: true
  - task: test
    file: destiny/ci/tasks/test/test.yml
